### ISSUE TITLE
Creating new project throwing error with the latest version of CLI

### ISSUE THREAD

**Issue by Abdurehman339** [nestjs/nest-cli#3112]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

Error: Cannot find module 'D:\Interview\nest-practice\"C:\Users\PMLS\AppData\Roaming\npm\node_modules\@nestjs\cli\node_modules\@angular-devkit\schematics-cli\bin\schematics.js"'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.17.0

Failed to execute command: node @nestjs/schematics:application --name=practice --directory=undefined --no-dry-run --no-skip-git --no-strict --package-manager="npm" --collection="@nestjs/schematics" --language="ts"

### Minimum reproduction code

https://github.com/nestjs/nest-cli

### Expected behavior

The command to create the new project should simply get the path to the schematic file and create the project, it's throwing error for now

### Package version

11.0.9

### Node.js version

20.19.4

### In which operating systems have you tested?

- [ ] macOS
- [x] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Duplicate

#3110

**Comment by irtaza-shahzad** [comment]
there is an issue with the latest version of nest (11.0.9). Try downgrading to a previous version. 

Run these commands in your terminal:

npm uninstall -g @nestjs/cli
npm install -g @nestjs/cli@11.0.7

this will temporarily fix your problem till the issue is fixed

**Comment by shhashwat** [comment]
> there is an issue with the latest version of nest (11.0.9). Try downgrading to a previous version.
> 
> Run these commands in your terminal:
> 
> npm uninstall -g @nestjs/cli npm install -g @nestjs/cli@11.0.7
> 
> this will temporarily fix your problem till the issue is fixed

I tried this and the nest new command worked, but it still fails at schematics, is there a work-around for that?

**Comment by huangshaomo** [comment]
same
